services:
  # Nama service untuk database PostgreSQL
  db:
    image: postgres:16-alpine # Guna official PostgreSQL image
    container_name: gengshop-db
    environment:
      # Environment variable untuk setup database
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5435:5432" # Boleh access dari laptop guna pgAdmin atau DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql/data # Simpan data supaya tak hilang bila container stop
    networks:
      - gengshop-network

# Define network yang akan digunakan
networks:
  gengshop-network:
    driver: bridge

# Define volume untuk simpan data database
volumes:
  postgres_data: